apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels:
    app: user
    tier: app
    project: roboshop
    
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: user
      tier: app
      project: roboshop
  template:
    metadata:
      labels:
        app: user
        tier: app
        project: roboshop
    spec:
      containers:
      - name: user
        image: {{ .Values.deployment.imageURL }}:{{ .Values.deployment.imageVersion }}
        envFrom:
        - configMapRef:
            name: user
        


    
