apiVersion: v1
kind: ConfigMap
metadata:
  name: dispatch
  namespace: roboshop
  labels:
    app: dispatch
    project: roboshop
    tier: app
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"