apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatch
  namespace: roboshop
  labels:
    app: dispatch
    tier: app
    project: roboshop
    
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: dispatch
      tier: app
      project: roboshop
  template:
    metadata:
      labels:
        app: dispatch
        tier: app
        project: roboshop
    spec:
      containers:
      - name: dispatch
        image: {{ .Values.deployment.imageURL }}:{{ .Values.deployment.imageVersion }}
        envFrom:
        - configMapRef:
            name: dispatch
        


    
