apiVersion: v1
kind: ConfigMap
metadata:
  name: payments
  namespace: roboshop
  labels:
    app: payments
    project: roboshop
    tier: app
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"